# Generated by Django 3.2.3 on 2021-05-22 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationrecord',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigationrecords', to='question_1.vehicle'),
        ),
    ]
